[def(register_depositor(%Keefe.RegisterDepositorInput{} = input)) do
  import(Lyex.Wsdl.Output, only: [read: 3])
  input = Keyword.get(binding(), :input)
  address = "https://services.keefegp.com/VendorPayment/VendorPaymentSvc.svc"
  headers = [{"Content-Type", "text/xml; charset=utf-8"}, {"SOAPAction", "http://www.keefecommissary.net/VendorPaymentService/v0101/IVendorPaymentSvc/RegisterDepositor"}, {"User-Agent", "Lyex/0.1.0"}, {"SOAP_Version", "1.1"}]
  envelope = EEx.eval_string("<soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'>        <soap:Header/>        <soap:Body>          <lyex:RegisterDepositor xmlns:lyex='http://www.keefecommissary.net/VendorPaymentService/v0101'>            <lyex:input><lyex:Zip><%= get_in(@input, [:input, :zip]) %></lyex:Zip><lyex:WorkPhone><%= get_in(@input, [:input, :work_phone]) %></lyex:WorkPhone><lyex:Username><%= get_in(@input, [:input, :username]) %></lyex:Username><lyex:State><%= get_in(@input, [:input, :state]) %></lyex:State><lyex:Password><%= get_in(@input, [:input, :password]) %></lyex:Password><lyex:MiddleName><%= get_in(@input, [:input, :middle_name]) %></lyex:MiddleName><lyex:LastName><%= get_in(@input, [:input, :last_name]) %></lyex:LastName><lyex:HomePhone><%= get_in(@input, [:input, :home_phone]) %></lyex:HomePhone><lyex:FirstName><%= get_in(@input, [:input, :first_name]) %></lyex:FirstName><lyex:FacilityCode><%= get_in(@input, [:input, :facility_code]) %></lyex:FacilityCode><lyex:Email><%= get_in(@input, [:input, :email]) %></lyex:Email><lyex:DepositAmount><%= get_in(@input, [:input, :deposit_amount]) %></lyex:DepositAmount><lyex:DOB><%= get_in(@input, [:input, :dob]) %></lyex:DOB><lyex:City><%= get_in(@input, [:input, :city]) %></lyex:City><lyex:CellPhone><%= get_in(@input, [:input, :cell_phone]) %></lyex:CellPhone><lyex:Auth><lyex:VendorCode><%= get_in(@input, [:auth, :input, :vendor_code]) %></lyex:VendorCode><lyex:UserId><%= get_in(@input, [:auth, :input, :user_id]) %></lyex:UserId><lyex:Password><%= get_in(@input, [:auth, :input, :password]) %></lyex:Password></lyex:Auth><lyex:AltEmail><%= get_in(@input, [:input, :alt_email]) %></lyex:AltEmail><lyex:Address2><%= get_in(@input, [:input, :address2]) %></lyex:Address2><lyex:Address1><%= get_in(@input, [:input, :address1]) %></lyex:Address1></lyex:input>          </lyex:RegisterDepositor>        </soap:Body>      </soap:Envelope>", assigns: [input: input])
  with({:ok, %{body: body}} <- HTTPoison.post(address, envelope, headers)) do
    read(body, "IVendorPaymentSvc_RegisterDepositor_OutputMessage", Keefe.RegisterDepositorOutput)
  end
end, def(pre_validate_deposit(%Keefe.PreValidateDepositInput{} = input)) do
  import(Lyex.Wsdl.Output, only: [read: 3])
  input = Keyword.get(binding(), :input)
  address = "https://services.keefegp.com/VendorPayment/VendorPaymentSvc.svc"
  headers = [{"Content-Type", "text/xml; charset=utf-8"}, {"SOAPAction", "http://www.keefecommissary.net/VendorPaymentService/v0101/IVendorPaymentSvc/PreValidateDeposit"}, {"User-Agent", "Lyex/0.1.0"}, {"SOAP_Version", "1.1"}]
  envelope = EEx.eval_string("<soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'>        <soap:Header/>        <soap:Body>          <lyex:PreValidateDeposit xmlns:lyex='http://www.keefecommissary.net/VendorPaymentService/v0101'>            <lyex:input><lyex:ResidentNumber><%= get_in(@input, [:input, :resident_number]) %></lyex:ResidentNumber><lyex:FacilityCode><%= get_in(@input, [:input, :facility_code]) %></lyex:FacilityCode><lyex:Auth><lyex:VendorCode><%= get_in(@input, [:auth, :input, :vendor_code]) %></lyex:VendorCode><lyex:UserId><%= get_in(@input, [:auth, :input, :user_id]) %></lyex:UserId><lyex:Password><%= get_in(@input, [:auth, :input, :password]) %></lyex:Password></lyex:Auth><lyex:Amount><%= get_in(@input, [:input, :amount]) %></lyex:Amount><lyex:AccountNumber><%= get_in(@input, [:input, :account_number]) %></lyex:AccountNumber></lyex:input>          </lyex:PreValidateDeposit>        </soap:Body>      </soap:Envelope>", assigns: [input: input])
  with({:ok, %{body: body}} <- HTTPoison.post(address, envelope, headers)) do
    read(body, "IVendorPaymentSvc_PreValidateDeposit_OutputMessage", Keefe.PreValidateDepositOutput)
  end
end, def(post_deposit(%Keefe.PostDepositInput{} = input)) do
  import(Lyex.Wsdl.Output, only: [read: 3])
  input = Keyword.get(binding(), :input)
  address = "https://services.keefegp.com/VendorPayment/VendorPaymentSvc.svc"
  headers = [{"Content-Type", "text/xml; charset=utf-8"}, {"SOAPAction", "http://www.keefecommissary.net/VendorPaymentService/v0101/IVendorPaymentSvc/PostDeposit"}, {"User-Agent", "Lyex/0.1.0"}, {"SOAP_Version", "1.1"}]
  envelope = EEx.eval_string("<soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'>        <soap:Header/>        <soap:Body>          <lyex:PostDeposit xmlns:lyex='http://www.keefecommissary.net/VendorPaymentService/v0101'>            <lyex:input><lyex:VendorTransId><%= get_in(@input, [:input, :vendor_trans_id]) %></lyex:VendorTransId><lyex:SurchargeFee><%= get_in(@input, [:input, :surcharge_fee]) %></lyex:SurchargeFee><lyex:ServiceFee><%= get_in(@input, [:input, :service_fee]) %></lyex:ServiceFee><lyex:ResidentNumber><%= get_in(@input, [:input, :resident_number]) %></lyex:ResidentNumber><lyex:PurposeCode><%= get_in(@input, [:input, :purpose_code]) %></lyex:PurposeCode><lyex:KeefeTransId><%= get_in(@input, [:input, :keefe_trans_id]) %></lyex:KeefeTransId><lyex:FacilityCode><%= get_in(@input, [:input, :facility_code]) %></lyex:FacilityCode><lyex:DepositorSSN><%= get_in(@input, [:input, :depositor_ssn]) %></lyex:DepositorSSN><lyex:DepositAmount><%= get_in(@input, [:input, :deposit_amount]) %></lyex:DepositAmount><lyex:Auth><lyex:VendorCode><%= get_in(@input, [:auth, :input, :vendor_code]) %></lyex:VendorCode><lyex:UserId><%= get_in(@input, [:auth, :input, :user_id]) %></lyex:UserId><lyex:Password><%= get_in(@input, [:auth, :input, :password]) %></lyex:Password></lyex:Auth><lyex:AmountCollected><%= get_in(@input, [:input, :amount_collected]) %></lyex:AmountCollected><lyex:AccountNumber><%= get_in(@input, [:input, :account_number]) %></lyex:AccountNumber></lyex:input>          </lyex:PostDeposit>        </soap:Body>      </soap:Envelope>", assigns: [input: input])
  with({:ok, %{body: body}} <- HTTPoison.post(address, envelope, headers)) do
    read(body, "IVendorPaymentSvc_PostDeposit_OutputMessage", Keefe.PostDepositOutput)
  end
end, def(lookup_recipient(%Keefe.LookupRecipientInput{} = input)) do
  import(Lyex.Wsdl.Output, only: [read: 3])
  input = Keyword.get(binding(), :input)
  address = "https://services.keefegp.com/VendorPayment/VendorPaymentSvc.svc"
  headers = [{"Content-Type", "text/xml; charset=utf-8"}, {"SOAPAction", "http://www.keefecommissary.net/VendorPaymentService/v0101/IVendorPaymentSvc/LookupRecipient"}, {"User-Agent", "Lyex/0.1.0"}, {"SOAP_Version", "1.1"}]
  envelope = EEx.eval_string("<soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'>        <soap:Header/>        <soap:Body>          <lyex:LookupRecipient xmlns:lyex='http://www.keefecommissary.net/VendorPaymentService/v0101'>            <lyex:input><lyex:RecipientNumber><%= get_in(@input, [:input, :recipient_number]) %></lyex:RecipientNumber><lyex:FacilityCode><%= get_in(@input, [:input, :facility_code]) %></lyex:FacilityCode><lyex:Auth><lyex:VendorCode><%= get_in(@input, [:auth, :input, :vendor_code]) %></lyex:VendorCode><lyex:UserId><%= get_in(@input, [:auth, :input, :user_id]) %></lyex:UserId><lyex:Password><%= get_in(@input, [:auth, :input, :password]) %></lyex:Password></lyex:Auth></lyex:input>          </lyex:LookupRecipient>        </soap:Body>      </soap:Envelope>", assigns: [input: input])
  with({:ok, %{body: body}} <- HTTPoison.post(address, envelope, headers)) do
    read(body, "IVendorPaymentSvc_LookupRecipient_OutputMessage", Keefe.LookupRecipientOutput)
  end
end, def(void_deposit(%Keefe.VoidDepositInput{} = input)) do
  import(Lyex.Wsdl.Output, only: [read: 3])
  input = Keyword.get(binding(), :input)
  address = "https://services.keefegp.com/VendorPayment/VendorPaymentSvc.svc"
  headers = [{"Content-Type", "text/xml; charset=utf-8"}, {"SOAPAction", "http://www.keefecommissary.net/VendorPaymentService/v0101/IVendorPaymentSvc/VoidDeposit"}, {"User-Agent", "Lyex/0.1.0"}, {"SOAP_Version", "1.1"}]
  envelope = EEx.eval_string("<soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'>        <soap:Header/>        <soap:Body>          <lyex:VoidDeposit xmlns:lyex='http://www.keefecommissary.net/VendorPaymentService/v0101'>            <lyex:input><lyex:VendorTransId><%= get_in(@input, [:input, :vendor_trans_id]) %></lyex:VendorTransId><lyex:ResidentNumber><%= get_in(@input, [:input, :resident_number]) %></lyex:ResidentNumber><lyex:KeefeTransId><%= get_in(@input, [:input, :keefe_trans_id]) %></lyex:KeefeTransId><lyex:FacilityCode><%= get_in(@input, [:input, :facility_code]) %></lyex:FacilityCode><lyex:Auth><lyex:VendorCode><%= get_in(@input, [:auth, :input, :vendor_code]) %></lyex:VendorCode><lyex:UserId><%= get_in(@input, [:auth, :input, :user_id]) %></lyex:UserId><lyex:Password><%= get_in(@input, [:auth, :input, :password]) %></lyex:Password></lyex:Auth><lyex:AccountNumber><%= get_in(@input, [:input, :account_number]) %></lyex:AccountNumber></lyex:input>          </lyex:VoidDeposit>        </soap:Body>      </soap:Envelope>", assigns: [input: input])
  with({:ok, %{body: body}} <- HTTPoison.post(address, envelope, headers)) do
    read(body, "IVendorPaymentSvc_VoidDeposit_OutputMessage", Keefe.VoidDepositOutput)
  end
end]